# INSPECT-SR <span class="badge badge-draft1">✎ Outline</span>

```{r}
#| include: false
if(file.exists("../_setup.R")){source("../_setup.R")}
```

## Overview

- The INSPECT-SR checklist for systematic reviewers assessing trustworthiness of included studies

## 1. Inspecting post-publication notices

- 1.1. Does the study have an associated retraction?
- 1.2. Does the study have an associated expression of concern or other relevant post-publication notice?
- 1.3. Do other studies by the research team highlight causes for concern (associated retractions, expressions of concern, relevant post-publication notices)?

## 2. Inspecting conduct, governance, and transparency

- 2.1. Are there concerns relating to ethical approval?
- 2.2. Are there concerns relating to the timing or absence of study registration?
- 2.3. Are there important inconsistencies between the publication and the registration documents?
- 2.4. Is the recruitment of participants implausible?
- 2.5. Are the reported methods implausible considering the reported resources?

## 3. Inspecting text and publication details

- 3.1. Are there concerns relating to duplicated content, such as text or tables, or text that is incompatible with the study?
- 3.2. Is there evidence of manipulation or duplication of figures?

## 4. Inspecting results in the study

- 4.1. Are there any unexplained discrepancies between reported data and participant eligibility criteria?
- 4.2. Are numbers of participants allocated to each group implausible given the allocation method?
- 4.3. Are any baseline data implausible?
- 4.4. Are there any discrepancies between results reported in figures, tables, and text?
- 4.5. Are the numbers of participants lost to follow-up implausible?
- 4.6. Are there any unexplained inconsistencies in the numbers of participants?
- 4.7. Are any outcome data, including estimated treatment effects, implausible?
- 4.8. Are the means and variances of integer data impossible?
- 4.9. Are there errors in statistical results?
- 4.10. Are any other contradictions implied by the data?
- 4.11. Are there inconsistencies in descriptions of methods and results across publications describing the study?
